// This file was auto-generated by prisma-generator-typescript-interfaces

export type UserRole = 'ADMIN' | 'MECANICO';

export type OrderStatus = 'RECIBIDO' | 'EN_PROCESO' | 'LISTO' | 'ENTREGADO';

export type OrderItemType = 'SERVICIO' | 'REPUESTO';

export type MediaType = 'IMAGEN' | 'VIDEO';

export interface Workshop {
  id: string;
  name: string;
  email: string;
  phone: string | null;
  address: string | null;
  /**
   * NIT del taller. En El Salvador es de 14 dígitos para persona jurídica,
   * pero una persona natural usa su DUI (9 dígitos) como NIT — por eso el
   * formato no se valida a nivel de schema.
   */
  nit: string | null;
  /**
   * Key del objeto en S3, no una URL: las URLs se firman al momento de leer.
   */
  logoKey: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface User {
  id: string;
  email: string;
  passwordHash: string;
  name: string;
  role: UserRole;
  workshopId: string;
  createdAt: string;
  updatedAt: string;
}

export interface Customer {
  id: string;
  name: string;
  phone: string;
  email: string | null;
  workshopId: string;
  createdAt: string;
  updatedAt: string;
}

export interface Vehicle {
  id: string;
  vin: string;
  plate: string | null;
  make: string | null;
  model: string | null;
  year: number | null;
  mileage: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface WorkOrder {
  id: string;
  status: OrderStatus;
  mileage: number | null;
  cost: string;
  notes: string | null;
  serviceDate: string;
  workshopId: string;
  vehicleId: string;
  customerId: string;
  createdAt: string;
  updatedAt: string;
}

export interface OrderItem {
  id: string;
  type: OrderItemType;
  description: string;
  quantity: number;
  unitPrice: string;
  workOrderId: string;
}

export interface MediaAsset {
  id: string;
  key: string;
  type: MediaType;
  contentType: string | null;
  sizeBytes: number | null;
  workOrderId: string;
  createdAt: string;
}
