// Auto-generated types — do not edit this file directly.
// Update apps/backend/prisma/schema.prisma and run `pnpm prisma generate`.

export type {
  UserRole,
  OrderStatus,
  OrderItemType,
  MediaType,
  Workshop,
  Customer,
  Vehicle,
  WorkOrder,
  OrderItem,
  MediaAsset,
} from './generated';

// User without server-only fields that must never leave the backend.
import type { User as _User } from './generated';
export type User = Omit<_User, 'passwordHash'>;
